name: GitHub action mvn build Example
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Step 1 - Check out main Branch
        uses: actions/checkout@v2
        
      - name: Step 2 - Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Step 3 - Maven GiHhub Actions Build Maven Project
        run: mvn -B package --file pom.xml
      
      - name: Step 4 - List out what is inside the current directory
        run: ls -a
      
      - name: Step4 - What is inside the Target Directory ?
        run: |
          cd target
          ls -a
          
          
    
